name: "Github Action to Slack - Simple way to send message to Slack from a Github Action"
description: "Send messages to Slack from your Github Actions. Supports Slack's required arguments as well as all the optional once"
branding:
  icon: "message-circle"
  color: "red"
inputs:
  slack-bot-user-oauth-access-token:
    description: "Bot User OAuth Access Token"
    required: true
  slack-channel:
    description: "Channel"
    required: true
  slack-text:
    description: "Text"
    required: true
  slack-optional-x:
    description: "Optional arguments"
    required: true
outputs:
  slack-result:
    description: "The result from the post to slack"
runs:
  using: "node12"
  main: "dist/index.js"
