name: "Github Actions Slack (simple with all optional arguments)"
description: "Post/send messages to Slack from your Github Actions. Supports the required arguments as well as all the optional once. "
inputs:
  slack-bot-user-oauth-access-token:
    description: "Bot User OAuth Access Token"
    required: true
  slack-channel:
    description: "Channel"
    required: true
  slack-text:
    description: "Text"
    required: true
  slack-optional-x:
    description: "Optional arguments"
    required: true
outputs:
  slack-result:
    description: "The result from the post to slack"
runs:
  using: "node12"
  main: "dist/index.js"
